office.presence.timeout-hours=${OFFICE_PRESENCE_TIMEOUT_HOURS:12}
neuland.authentik.issuer=${NEULAND_AUTHENTIK_ISSUER:https://auth.neuland.ing/application/o/next/}
neuland.authentik.client-id=${NEULAND_AUTHENTIK_CLIENT_ID}
quarkus.http.host=0.0.0.0
