office.presence.timeout-hours=${OFFICE_PRESENCE_TIMEOUT_HOURS:12}
neuland.authentik.issuer=${NEULAND_AUTHENTIK_ISSUER}
neuland.authentik.client-id=${NEULAND_AUTHENTIK_CLIENT_ID}
quarkus.http.host=0.0.0.0
quarkus.ssl.native=true
quarkus.native.additional-build-args=\
  --enable-url-protocols=https,\
  --initialize-at-run-time=org.jose4j.jwk.HttpsJwks,\
  --initialize-at-run-time=org.jose4j.http.Get
